/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConsultarProdutoGUI.java
 *
 * Created on 02/06/2011, 03:08:41
 */
package br.com.sig.view;

import br.com.sig.dao.DestinoDAO;
import br.com.medicalpharm.model.ArmazemModel;
import br.com.sig.util.ItemDbGrid;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ALENCAR
 */
public class DestinoConsultarGUI1 extends javax.swing.JFrame {

    SaidaEstoqueGUI janelapai2;
    ArmazemCadastroGUI janelapai4;
    EntradaCadastraGUI janelapai;
    AjusteEstoqueGUI janelapai3;

    public DestinoConsultarGUI1() {
        initComponents();

        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            // UIManager.setLookAndFeel("com.sun.java.swing.plaf.smoothmetal.SmoothmetalLookAndAndFeel");
            //UIManager.setLookAndFeel("com.birosoft.liquid.LiquidLookAndFeel");
            //UIManager.setLookAndFeel(seta_look);
            SwingUtilities.updateComponentTreeUI(this);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro);
        }

        janelapai = null;
        janelapai2 = null;
        janelapai3 = null;
        janelapai4 = null;
    }
    List<ArmazemModel> armazens;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jb_cancelar = new javax.swing.JButton();
        jb_ok = new javax.swing.JButton();
        jb_novo1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Consulta Almoxarifado");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/medicalpharm/image/exit.png"))); // NOI18N
        jb_cancelar.setText("Cancelar");
        jb_cancelar.setName("jb_cancelar"); // NOI18N
        jb_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jb_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 110, 40));

        jb_ok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/medicalpharm/image/gravar_registro.gif"))); // NOI18N
        jb_ok.setText("OK");
        jb_ok.setName("jb_ok"); // NOI18N
        jb_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_okActionPerformed(evt);
            }
        });
        getContentPane().add(jb_ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 80, 40));

        jb_novo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/medicalpharm/image/novo_registro.gif"))); // NOI18N
        jb_novo1.setText("Novo");
        jb_novo1.setName("jb_novo1"); // NOI18N
        jb_novo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_novo1ActionPerformed(evt);
            }
        });
        getContentPane().add(jb_novo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 110, 40));

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setUpdateSelectionOnSort(false);
        jTable1.setVerifyInputWhenFocusTarget(false);
        jTable1.setDefaultEditor(Object.class, null);
        jTable1.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e){
                if(e.getClickCount() == 2){
                    botaoOK(jTable1);

                }}});
                jTable1.setModel(new javax.swing.table.DefaultTableModel(
                    new Object [][] {

                    },
                    new String [] {
                        "Código", "Descrição"
                    }
                ) {
                    Class[] types = new Class [] {
                        java.lang.String.class, java.lang.Object.class
                    };
                    boolean[] canEdit = new boolean [] {
                        false, false
                    };

                    public Class getColumnClass(int columnIndex) {
                        return types [columnIndex];
                    }

                    public boolean isCellEditable(int rowIndex, int columnIndex) {
                        return canEdit [columnIndex];
                    }
                });
                jTable1.setName("jTable1"); // NOI18N
                jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
                    public void keyPressed(java.awt.event.KeyEvent evt) {
                        jTable1KeyPressed(evt);
                    }
                });
                jScrollPane1.setViewportView(jTable1);
                if (jTable1.getColumnModel().getColumnCount() > 0) {
                    jTable1.getColumnModel().getColumn(0).setPreferredWidth(10);
                    jTable1.getColumnModel().getColumn(1).setPreferredWidth(250);
                }

                getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 430, 330));

                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/medicalpharm/image/icone-armazens-gerais.png"))); // NOI18N
                jLabel1.setName("jLabel1"); // NOI18N
                getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, 60));

                jLabel2.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
                jLabel2.setText("Almoxarifados encontrados");
                jLabel2.setName("jLabel2"); // NOI18N
                getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 390, -1));

                setSize(new java.awt.Dimension(516, 535));
                setLocationRelativeTo(null);
            }// </editor-fold>//GEN-END:initComponents

    private void jb_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cancelarActionPerformed
        setVisible(false);
        if ((janelapai != null)) {
            janelapai.setEnabled(true);
            janelapai.setVisible(true);
            //telaCadNota.setStatusTela(false);
        }
        if ((janelapai2 != null)) {
            janelapai2.setEnabled(true);
            janelapai2.setVisible(true);
        }

        if ((janelapai3 != null)) {
            janelapai3.setEnabled(true);
            janelapai3.setVisible(true);
        }
        if ((janelapai4 != null)) {
            janelapai4.setEnabled(true);
            janelapai4.setVisible(true);
        }
}//GEN-LAST:event_jb_cancelarActionPerformed
    private EntradaCadastraGUI_InterFace telaCadNota;
    private SaidaEstoqueGUI_interface telaSaidaEstoque;
    private AjusteEstoqueGUI_Interface telaAjusteEstoque;
    private ArmazemCadastroGUI_Interface telaArmazemEstoque;

    private void jb_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_okActionPerformed

        botaoOK(jTable1);

}//GEN-LAST:event_jb_okActionPerformed
    public void botaoOK(JTable tb) {
        if(tb.getSelectedRow() != -1){
        setVisible(false);

        ArmazemModel arm = tbArmazemLinhaSelecionada(jTable1);
        if ((janelapai2 != null) && (arm != null)) {
            janelapai2.setEnabled(true);
            janelapai2.setVisible(true);
            telaSaidaEstoque.carregaDestino(arm);
            // telaAjusteEstoque.carregaFornecedor(arm);
            //telaCadNota.setStatusTela(false);
        }


        if ((janelapai4 != null) && (arm != null)) {
            janelapai4.setEnabled(true);
            janelapai4.setVisible(true);
            telaArmazemEstoque.carregaDestino(arm);
            //telaSaidaEstoque.statusTela(true);        
        }

    } else {
            JOptionPane.showMessageDialog(null, "Selecione um armazém");
        }
      
    }
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        setVisible(false);
        if ((janelapai != null)) {
            janelapai.setEnabled(true);
            janelapai.setVisible(true);
            //telaCadNota.setStatusTela(false);
        }


        if ((janelapai3 != null)) {
            janelapai3.setEnabled(true);
            janelapai3.setVisible(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void jb_novo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_novo1ActionPerformed
        DestinoCadastroGUI des = new DestinoCadastroGUI();
        des.janelapai4 = this;
        des.setVisible(true);
        this.setEnabled(false);
        // TODO add your handling code here:
}//GEN-LAST:event_jb_novo1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//        jt_pesquisar.getColumnModel().getColumn( 3 ).setMaxWidth( 60 );
//        jt_pesquisar.getColumnModel().getColumn( 3 ).setMinWidth( 60 );
//        jt_pesquisar.getTableHeader().getColumnModel().getColumn( 3 ).setMaxWidth( 60 );
//        jt_pesquisar.getTableHeader().getColumnModel().getColumn( 3 ).setMinWidth( 60 );
    }//GEN-LAST:event_formWindowOpened

private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
//    if(jTable1.getSelectedRow()== 1){                           
        botaoOK(jTable1);
        //  }
    }
    // TODO add your handling code here:
}//GEN-LAST:event_jTable1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new DestinoConsultarGUI1().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jb_cancelar;
    private javax.swing.JButton jb_novo1;
    private javax.swing.JButton jb_ok;
    // End of variables declaration//GEN-END:variables

    //Recebendo tela como parametro para atualização apos pesquisa
    public void setTelaCadNota(EntradaCadastraGUI_InterFace telaCadNota) {
        this.telaCadNota = telaCadNota;
    }

    public void setTelaAjusteEstoque(AjusteEstoqueGUI_Interface telaAjusteEstoque) {
        this.telaAjusteEstoque = telaAjusteEstoque;
    }

    public void setTelaArmazem(ArmazemCadastroGUI_Interface telaArmazemEstoque) {
        this.telaArmazemEstoque = telaArmazemEstoque;
    }

    public void setTelaSaidaEstoque(SaidaEstoqueGUI_interface telaSaidaEstoque) {
        this.telaSaidaEstoque = telaSaidaEstoque;
    }

    public void setCadastro() {
        jb_novo1.setEnabled(false);
    }

    public ArmazemModel tbArmazemLinhaSelecionada(JTable tb) {
        ArmazemModel arm = null;
        if (tb.getSelectedRow() != -1) {
            arm = new ArmazemModel();
            arm.setCod_destino(armazens.get(tb.getSelectedRow()).getCod_destino());
            arm.setDesc_destino(armazens.get(tb.getSelectedRow()).getDesc_destino());
        }
        return arm;
    }

    public void listaArmazem(String consulta) {
        DestinoDAO dest = new DestinoDAO();
        armazens = dest.listarDestino("%" + consulta + "%");
        mostraDestinos(armazens);
    }

    public void mostraDestinos(List<ArmazemModel> armazens) {
        ((DefaultTableModel) jTable1.getModel()).setRowCount(0);
        jTable1.updateUI();

        if (armazens.size() == 0) {
            JOptionPane.showMessageDialog(this, "Nenhum armazém encontrado");

        } else {
            for (int i = 0; i < armazens.size(); i++) {
                ArmazemModel arm = new ArmazemModel();
                arm.setCod_destino(armazens.get(i).getCod_destino());
                arm.setDesc_destino(armazens.get(i).getDesc_destino());

                DefaultTableModel row = (DefaultTableModel) jTable1.getModel();
                ItemDbGrid hashDbGrid = new ItemDbGrid(arm, arm.getDesc_destino());
                row.addRow(new Object[]{arm.getCod_destino(), hashDbGrid});
            }
            jTable1.setSelectionMode(1);
        }
    }
}
