/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GrupoCadastroGUI.java
 *
 * Created on 23/05/2011, 22:34:40
 */
package br.com.sig.view;

import br.com.sig.dao.GrupoDAO;
import br.com.medicalpharm.model.GrupoModel;
import br.com.medicalpharm.model.SubGrupoModel;
import br.com.sig.util.LimitadorTexto;
import br.com.sig.util.UnaccentedDocument;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ALENCAR
 */
public class GrupoCadastroGUI extends javax.swing.JFrame {

    public List<GrupoModel> grupos;

    /** Creates new form GrupoCadastroGUI */
    public GrupoCadastroGUI() {
        initComponents();
        janelapai = null;
        janelapai2 = null;
        janelapai3 = null;
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            // UIManager.setLookAndFeel("com.sun.java.swing.plaf.smoothmetal.SmoothmetalLookAndAndFeel");
            //UIManager.setLookAndFeel("com.birosoft.liquid.LiquidLookAndFeel");
            //UIManager.setLookAndFeel(seta_look);
            SwingUtilities.updateComponentTreeUI(this);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro);
        }

    }
    public GrupoGUI janelapai;
    public ProdutoCadastroGUI janelapai2;
    public ProdutoAlterarGUI janelapai3;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jtf_cod_grupo = new javax.swing.JTextField();
        jtf_desc_grupo = new javax.swing.JTextField(new LimitadorTexto(45), "",10);
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jb_salvar = new javax.swing.JButton();
        jb_cancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jtf_subDesc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jTextField2.setText("jTextField2");
        jTextField2.setName("jTextField2"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrando Grupo");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Grupo"));
        jPanel2.setName("jPanel2"); // NOI18N

        jtf_cod_grupo.setEditable(false);
        jtf_cod_grupo.setName("jtf_cod_grupo"); // NOI18N

        jtf_desc_grupo.setDocument(new UnaccentedDocument());
        jtf_desc_grupo.setName("jtf_desc_grupo"); // NOI18N
        jtf_desc_grupo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtf_desc_grupoFocusGained(evt);
            }
        });
        jtf_desc_grupo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_desc_grupoKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setText("Código");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setText("Descrição");
        jLabel2.setName("jLabel2"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtf_desc_grupo, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(jtf_cod_grupo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addComponent(jtf_cod_grupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_desc_grupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jb_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/medicalpharm/image/gravar_registro.gif"))); // NOI18N
        jb_salvar.setText("Salvar");
        jb_salvar.setName("jb_salvar"); // NOI18N
        jb_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_salvarActionPerformed(evt);
            }
        });

        jb_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/medicalpharm/image/exit.png"))); // NOI18N
        jb_cancelar.setText("Cancelar");
        jb_cancelar.setName("jb_cancelar"); // NOI18N
        jb_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cancelarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Sub-Grupo"));
        jPanel1.setName("jPanel1"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sub-Grupo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setColumnSelectionAllowed(true);
        jTable1.setName("jTable1"); // NOI18N
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jtf_subDesc.setDocument(new UnaccentedDocument());
        jtf_subDesc.setName("jtf_subDesc"); // NOI18N
        jtf_subDesc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_subDescKeyPressed(evt);
            }
        });

        jLabel3.setText("Descrição");
        jLabel3.setName("jLabel3"); // NOI18N

        jButton1.setText("+");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("-");
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jtf_subDesc)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton2))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_subDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(jButton1)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jb_salvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb_cancelar)))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_salvar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );

        setSize(new java.awt.Dimension(479, 499));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jb_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_salvarActionPerformed
       if(verificarCampos()==true){
           verificaCadastro();
       }

    }//GEN-LAST:event_jb_salvarActionPerformed
    public void retornaJanelapai() {
        setVisible(false);

        if (janelapai != null) {
            janelapai.listarGrupo();
            janelapai.setEnabled(true);
            janelapai.setVisible(true);
            janelapai.request();
        }
        if (janelapai2 != null) {
            janelapai2.listarGrupo();
            janelapai2.setEnabled(true);
            janelapai2.setVisible(true);

        }
        if (janelapai3 != null) {
            janelapai3.listarGrupo();
            janelapai3.setEnabled(true);
            janelapai3.setVisible(true);

        }


    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jtf_desc_grupo.requestFocus();
    }//GEN-LAST:event_formWindowOpened

    private void jb_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cancelarActionPerformed
        retornaJanelapai();
    }//GEN-LAST:event_jb_cancelarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        retornaJanelapai();
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void jtf_desc_grupoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_desc_grupoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            verificaCadastro();
        }
            jtf_desc_grupo.addKeyListener(new KeyAdapter() {  
      public void keyReleased(KeyEvent evt) {  
        if (evt.getKeyCode() != KeyEvent.VK_HOME) {  
          String s = jtf_desc_grupo.getText();  
          jtf_desc_grupo.setText(s.toUpperCase());  
        }  
      }  
    }); 
    
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_desc_grupoKeyPressed

    private void jtf_desc_grupoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtf_desc_grupoFocusGained
//        jtf_desc_grupo.setInputVerifier(new InputVerifier() {
//
//            public boolean verify(JComponent input) {
//                if (jtf_desc_grupo.getText().equals("(  )    -    ")) {
//                    JOptionPane.showMessageDialog(null, "Informe a descrição do grupo");
//                    jtf_desc_grupo.requestFocus();
//                    return false;
//                } else {
//                    return true;
//                }
//            }
//        });
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_desc_grupoFocusGained
    public void limparItem() {
        jtf_subDesc.setText("");
    }
    SubGrupoModel sub = new SubGrupoModel();
private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    if (!(jtf_subDesc.getText().equals(""))) {
        sub.setDescSubGrupo(jtf_subDesc.getText());

        DefaultTableModel row = (DefaultTableModel) jTable1.getModel();
        row.addRow(new Object[]{sub.getDescSubGrupo()});
//    ItemDbGrid hashDbGrid = new ItemDbGrid(sub, sub.getDescSubGrupo());
//    row.addRow(new Object[]{hashDbGrid});

        limparItem();
        jtf_subDesc.requestFocus();

    } else {
        JOptionPane.showMessageDialog(null, "Informe o subgrupo");
    }


    // TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed
    private void excluirSub() {
        removeProduto(jTable1);
    }

    public void removeProduto(JTable tb) {
        DefaultTableModel row = (DefaultTableModel) jTable1.getModel();
        if (tb.getSelectedRow() != -1) {
            int selectedOption = JOptionPane.showConfirmDialog(this, "Deseja excluir ?", "Atenção", JOptionPane.YES_NO_OPTION);
            if (selectedOption == JOptionPane.YES_NO_OPTION) {
                row.removeRow(tb.getSelectedRow());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um Sub-Grupo");
        }
    }
private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    excluirSub();

    // TODO add your handling code here:
}//GEN-LAST:event_jButton2ActionPerformed

private void jtf_subDescKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_subDescKeyPressed
            jtf_subDesc.addKeyListener(new KeyAdapter() {  
      public void keyReleased(KeyEvent evt) {  
        if (evt.getKeyCode() != KeyEvent.VK_HOME) {  
          String s = jtf_subDesc.getText();  
          jtf_subDesc.setText(s.toUpperCase());  
        }  
      }  
    }); 
    // TODO add your handling code here:
}//GEN-LAST:event_jtf_subDescKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new GrupoCadastroGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton jb_cancelar;
    private javax.swing.JButton jb_salvar;
    private javax.swing.JTextField jtf_cod_grupo;
    private javax.swing.JTextField jtf_desc_grupo;
    private javax.swing.JTextField jtf_subDesc;
    // End of variables declaration//GEN-END:variables

    private void cadastraGrupo() {
        if (verificarCampos()) {
            List<SubGrupoModel> itens = new ArrayList();
            for (int i = 0; i < jTable1.getRowCount(); i++) {
                SubGrupoModel sub = new SubGrupoModel();
                sub.setDescSubGrupo((String) jTable1.getValueAt(i, 0));
                itens.add(sub);
            }

            GrupoModel grupo = new GrupoModel();
            grupo.setDesc_grupo(jtf_desc_grupo.getText().trim());
            GrupoDAO grupoControl = new GrupoDAO();
            grupo = grupoControl.cadastraGrupo(grupo);
            if (grupo != null) {
                grupoControl.cadastraSubGrupo(itens, grupo);
                JOptionPane.showMessageDialog(null, "Cadastrado efetuado com sucesso");
                retornaJanelapai();
            } else {
                JOptionPane.showMessageDialog(null, "Erro sub grupo");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Sub Grupo - erro ");
        }
    }

    public boolean verificarCampos() {
        String msgERRO = "Preencha os campos obrigatórios:\n";

        if (jtf_desc_grupo.getText().trim().equals("")) {
            msgERRO = msgERRO + " *Descrição\n";

        }
        if (jTable1.getRowCount() == 0) {
            msgERRO = msgERRO + " *Adicione pelo menos 1 Sub-Grupo\n";
        }
        if (!msgERRO.equals("Preencha os campos obrigatórios:\n")) {
            JOptionPane.showMessageDialog(this, msgERRO);
            jtf_desc_grupo.requestFocus();
            return false;
        } else {

            return true;
        }
    }

    public void verificaCadastro() {
        GrupoDAO grup = new GrupoDAO();
        grupos = grup.listarGrupoDescricao(jtf_desc_grupo.getText().trim());
        validaCadastro(grupos);
    }

    public void validaCadastro(List<GrupoModel> grupo) {//verifica cadastro existente que retornou de uma lista

        if (grupo.size() == 0) {
            cadastraGrupo();
        } else {
            JOptionPane.showMessageDialog(null, "Grupo existente");
            jtf_desc_grupo.requestFocus();
        }
    }
}
