/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RelatórioGUI.java
 *
 * Created on 25/08/2011, 12:24:36
 */
package br.com.sig.view;

import br.com.sig.dao.DestinoDAO;
import br.com.sig.dao.GrupoDAO;
import br.com.medicalpharm.model.ArmazemModel;
import br.com.medicalpharm.model.GrupoModel;
import br.com.sig.relatorios.Relatorios;
import br.com.sig.util.ItemDbGrid;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author ALENCAR
 */
public class RelatórioGUI extends javax.swing.JFrame {

    /** Creates new form RelatórioGUI */
    public RelatórioGUI() {
        initComponents();
        listarGrupo();
        listarDestino();
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            // UIManager.setLookAndFeel("com.sun.java.swing.plaf.smoothmetal.SmoothmetalLookAndAndFeel");
            //UIManager.setLookAndFeel("com.birosoft.liquid.LiquidLookAndFeel");
            //UIManager.setLookAndFeel(seta_look);
            SwingUtilities.updateComponentTreeUI(this);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro);
        }
    }
    MaskFormatter formatoData;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButton5 = new javax.swing.JRadioButton();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jrb_itensEstoque = new javax.swing.JRadioButton();
        jrb_quantidadeAbaixo = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jrb_minima = new javax.swing.JRadioButton();
        jrb_ideal = new javax.swing.JRadioButton();
        jrb_listamCompleta = new javax.swing.JRadioButton();
        jrb_movimento = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jl_grupo = new javax.swing.JLabel();
        jcb_grupo = new javax.swing.JComboBox();
        jb_cancelar = new javax.swing.JButton();
        jb_gerar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jrb_ordenarProduto = new javax.swing.JRadioButton();
        jrb_ordenarGrupo = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        try  {      
            formatoData = new MaskFormatter("##/##/####");  
        } 
        catch (Exception erro)  
        {    
            JOptionPane.showMessageDialog(null,"Não foi possivel setar");  
        }
        jftf_data = new JFormattedTextField(formatoData);
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        try  {      
            formatoData = new MaskFormatter("##/##/####");  
        } 
        catch (Exception erro)  
        {    
            JOptionPane.showMessageDialog(null,"Não foi possivel setar");  
        }
        jftf_data1 = new JFormattedTextField(formatoData);
        jcb_destino = new javax.swing.JComboBox();

        jRadioButton5.setText("jRadioButton5");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatórios");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Tipos"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup2.add(jrb_itensEstoque);
        jrb_itensEstoque.setSelected(true);
        jrb_itensEstoque.setText("Estoque central");
        jrb_itensEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_itensEstoqueActionPerformed(evt);
            }
        });
        jPanel1.add(jrb_itensEstoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        buttonGroup2.add(jrb_quantidadeAbaixo);
        jrb_quantidadeAbaixo.setText("Itens com quantidade abaixo da ");
        jrb_quantidadeAbaixo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_quantidadeAbaixoActionPerformed(evt);
            }
        });
        jPanel1.add(jrb_quantidadeAbaixo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buttonGroup1.add(jrb_minima);
        jrb_minima.setSelected(true);
        jrb_minima.setText("mínima");

        buttonGroup1.add(jrb_ideal);
        jrb_ideal.setText("ideal");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jrb_minima)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrb_ideal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jrb_minima)
                .addComponent(jrb_ideal))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, -1));

        buttonGroup2.add(jrb_listamCompleta);
        jrb_listamCompleta.setText("Relação dos produtos cadastrados");
        jrb_listamCompleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_listamCompletaActionPerformed(evt);
            }
        });
        jPanel1.add(jrb_listamCompleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        buttonGroup2.add(jrb_movimento);
        jrb_movimento.setText("Movimentação por almoxarifado");
        jrb_movimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_movimentoActionPerformed(evt);
            }
        });
        jPanel1.add(jrb_movimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 460, 150));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Critério"));

        jl_grupo.setText("Grupo:");

        jcb_grupo.setEditable(true);
        jcb_grupo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Todos>" }));
        jcb_grupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_grupoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_grupo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcb_grupo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_grupo)
                    .addComponent(jcb_grupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jb_cancelar.setText("Sair");
        jb_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jb_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, -1, -1));

        jb_gerar.setText("Gerar");
        jb_gerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_gerarActionPerformed(evt);
            }
        });
        getContentPane().add(jb_gerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 93, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Ordem"));

        buttonGroup3.add(jrb_ordenarProduto);
        jrb_ordenarProduto.setSelected(true);
        jrb_ordenarProduto.setText("Ordenada por produto");

        buttonGroup3.add(jrb_ordenarGrupo);
        jrb_ordenarGrupo.setText("Ordenada pelo grupo do produto");
        jrb_ordenarGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_ordenarGrupoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrb_ordenarProduto)
                    .addComponent(jrb_ordenarGrupo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jrb_ordenarProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrb_ordenarGrupo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 210, -1));

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jftf_data.setEnabled(false);
        jftf_data.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jftf_dataFocusLost(evt);
            }
        });
        jftf_data.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jftf_dataKeyPressed(evt);
            }
        });

        jLabel1.setText("Data:");

        jLabel2.setText("a");

        jftf_data1.setEnabled(false);
        jftf_data1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jftf_data1FocusLost(evt);
            }
        });
        jftf_data1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jftf_data1KeyPressed(evt);
            }
        });

        jcb_destino.setEditable(true);
        jcb_destino.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Todos>" }));
        jcb_destino.setEnabled(false);
        jcb_destino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_destinoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcb_destino, 0, 436, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(15, 15, 15)
                        .addComponent(jftf_data, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jftf_data1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jftf_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jftf_data1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcb_destino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, 80));

        setSize(new java.awt.Dimension(517, 506));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jrb_itensEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_itensEstoqueActionPerformed
        if (jrb_itensEstoque.isSelected()) {
            jcb_destino.setEnabled(false);
            jrb_ordenarProduto.setEnabled(true);
            jrb_ordenarGrupo.setEnabled(true);
            jcb_grupo.setEnabled(true);
            jl_grupo.setEnabled(true);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jrb_itensEstoqueActionPerformed
    TelaPrincipal janelapai;
    private TelaPrincipal_Interface telaPrincipal;//Recebendo tela como parametro para atualização apos pesquisa

    public void setTelaPrincipal(TelaPrincipal_Interface telaPrincipal) {
        this.telaPrincipal = telaPrincipal;
    }
    private void jb_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cancelarActionPerformed
        setVisible(false);
        telaPrincipal.setStatusTela(true);
        // TODO add your handling code here:
}//GEN-LAST:event_jb_cancelarActionPerformed

    private void jcb_grupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_grupoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jcb_grupoActionPerformed

    private void jb_gerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_gerarActionPerformed
        if (jrb_itensEstoque.isSelected() && jrb_ordenarProduto.isSelected()) {

            if (jcb_grupo.getSelectedIndex() == 0) {
                Relatorios relatorio = new Relatorios();
                relatorio.setRelatorioEstoqueProduto();
            } else {
                ItemDbGrid hashDbGrid = (ItemDbGrid) jcb_grupo.getSelectedItem();
                GrupoModel grupo = (GrupoModel) hashDbGrid.getObjeto();
                Relatorios relatorio = new Relatorios();
                relatorio.setRelatorioEstoqueProduto1(grupo);
            }

        }
        if (jrb_itensEstoque.isSelected() && jrb_ordenarGrupo.isSelected()) {

            if (jcb_grupo.getSelectedIndex() == 0) {
                Relatorios relatorio = new Relatorios();
                relatorio.setRelatorioEstoqueGrupo();
            } else {
                ItemDbGrid hashDbGrid = (ItemDbGrid) jcb_grupo.getSelectedItem();
                GrupoModel grupo = (GrupoModel) hashDbGrid.getObjeto();
                Relatorios relatorio = new Relatorios();
                relatorio.setRelatorioEstoqueGrupo1(grupo);
            }

        }

        //ordenar todos por produto
        if (jrb_listamCompleta.isSelected() && jrb_ordenarProduto.isSelected()) {

            if (jcb_grupo.getSelectedIndex() == 0) {
                Relatorios relatorio = new Relatorios();
                relatorio.setRelatorioProduto();
            } else {
                ItemDbGrid hashDbGrid = (ItemDbGrid) jcb_grupo.getSelectedItem();
                GrupoModel grupo = (GrupoModel) hashDbGrid.getObjeto();
                Relatorios relatorio = new Relatorios();
                relatorio.setRelatorioProduto1(grupo);
            }

        }
        //ordenar todos por grupo
        if (jrb_listamCompleta.isSelected() && jrb_ordenarGrupo.isSelected()) {

            if (jcb_grupo.getSelectedIndex() == 0) {
                Relatorios relatorio = new Relatorios();
                relatorio.setRelatorioGrupo();
            } else {
                ItemDbGrid hashDbGrid = (ItemDbGrid) jcb_grupo.getSelectedItem();
                GrupoModel grupo = (GrupoModel) hashDbGrid.getObjeto();
                Relatorios relatorio = new Relatorios();
                relatorio.setRelatorioGrupo1(grupo);
            }

        }




        if (jrb_quantidadeAbaixo.isSelected() && jrb_minima.isSelected() && jrb_ordenarProduto.isSelected()) {

            if (jcb_grupo.getSelectedIndex() == 0) {
                Relatorios relatorio = new Relatorios();
                relatorio.setEstoqueMinimoProduto();
            } else {
                ItemDbGrid hashDbGrid = (ItemDbGrid) jcb_grupo.getSelectedItem();
                GrupoModel grupo = (GrupoModel) hashDbGrid.getObjeto();
                Relatorios relatorio = new Relatorios();
                relatorio.setEstoqueMinimoProduto(grupo);
            }
        }
        if (jrb_quantidadeAbaixo.isSelected() && jrb_minima.isSelected() && jrb_ordenarGrupo.isSelected()) {

            if (jcb_grupo.getSelectedIndex() == 0) {
                Relatorios relatorio = new Relatorios();
                relatorio.setEstoqueMinimoGrupo();
            } else {
                ItemDbGrid hashDbGrid = (ItemDbGrid) jcb_grupo.getSelectedItem();
                GrupoModel grupo = (GrupoModel) hashDbGrid.getObjeto();
                Relatorios relatorio = new Relatorios();
                relatorio.setEstoqueMinimoGrupo(grupo);
            }
        }



        if (jrb_quantidadeAbaixo.isSelected() && jrb_ideal.isSelected() && jrb_ordenarProduto.isSelected()) {

            if (jcb_grupo.getSelectedIndex() == 0) {
                Relatorios relatorio = new Relatorios();
                relatorio.setEstoqueIdealProduto();
            } else {
                ItemDbGrid hashDbGrid = (ItemDbGrid) jcb_grupo.getSelectedItem();
                GrupoModel grupo = (GrupoModel) hashDbGrid.getObjeto();
                Relatorios relatorio = new Relatorios();
                relatorio.setEstoqueIdealProduto(grupo);
            }


        }
        if (jrb_quantidadeAbaixo.isSelected() && jrb_ideal.isSelected() && jrb_ordenarGrupo.isSelected()) {

            if (jcb_grupo.getSelectedIndex() == 0) {
                Relatorios relatorio = new Relatorios();
                relatorio.setEstoqueIdealGrupo();
            } else {
                ItemDbGrid hashDbGrid = (ItemDbGrid) jcb_grupo.getSelectedItem();
                GrupoModel grupo = (GrupoModel) hashDbGrid.getObjeto();
                Relatorios relatorio = new Relatorios();
                relatorio.setEstoqueIdealGrupo(grupo);
            }


        }
        if (jrb_movimento.isSelected()) {

            if (jcb_destino.getSelectedIndex() == 0) {
                if (jftf_data.getText().equals("  /  /    ") || jftf_data1.getText().equals("  /  /    ")) {
                    JOptionPane.showMessageDialog(null, "Informe uma data como parametro");
                    jftf_data.requestFocus();
                } else {
                    Date data1 = null;
                    Date data2 = null;
                    try {
                        data1 = new SimpleDateFormat("dd/MM/yyyy").parse(jftf_data.getText());

                        data2 = new SimpleDateFormat("dd/MM/yyyy").parse(jftf_data1.getText());
                    } catch (ParseException ex) {
                        Logger.getLogger(RelatórioGUI.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    Relatorios relatorio = new Relatorios();
                    relatorio.setMovimentoDestino(data1, data2);

                }
            } else {
                if (jftf_data.getText().equals("  /  /    ") || jftf_data1.getText().equals("  /  /    ")) {
                    JOptionPane.showMessageDialog(null, "Informe uma data como parametro");
                    jftf_data.requestFocus();
                } else {
                    Date data1 = null;
                    Date data2 = null;
                    try {
                        data1 = new SimpleDateFormat("dd/MM/yyyy").parse(jftf_data.getText());

                        data2 = new SimpleDateFormat("dd/MM/yyyy").parse(jftf_data1.getText());
                    } catch (ParseException ex) {
                        Logger.getLogger(RelatórioGUI.class.getName()).log(Level.SEVERE, null, ex);
                    }


                    ItemDbGrid hashDbGrid = (ItemDbGrid) jcb_destino.getSelectedItem();
                    ArmazemModel destino = (ArmazemModel) hashDbGrid.getObjeto();
                    Relatorios relatorio = new Relatorios();
                    relatorio.setMovimentoDestino(destino, data1, data2);

                }
            }


        }

//        if (jrb_vencidos.isSelected()) {
//            Relatorios relatorio = new Relatorios();
//            relatorio.setVencidos();
//
//        }
}//GEN-LAST:event_jb_gerarActionPerformed

    private void jrb_ordenarGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_ordenarGrupoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrb_ordenarGrupoActionPerformed

    private void jrb_movimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_movimentoActionPerformed
        if (jrb_movimento.isSelected()) {
            jcb_destino.setEnabled(true);
            jrb_ordenarProduto.setEnabled(false);
            jrb_ordenarGrupo.setEnabled(false);
            jcb_grupo.setEnabled(false);
            jl_grupo.setEnabled(false);
            jftf_data.setEnabled(true);
            jftf_data1.setEnabled(true);
            jftf_data.requestFocus();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jrb_movimentoActionPerformed

    private void jrb_listamCompletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_listamCompletaActionPerformed
        if (jrb_listamCompleta.isSelected()) {
            jcb_destino.setEnabled(false);
            jrb_ordenarProduto.setEnabled(true);
            jrb_ordenarGrupo.setEnabled(true);
            jcb_grupo.setEnabled(true);
            jl_grupo.setEnabled(true);
            jftf_data.setEnabled(false);
            jftf_data1.setEnabled(false);
            jftf_data.setText("");
            jftf_data1.setText("");
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_jrb_listamCompletaActionPerformed

    private void jrb_quantidadeAbaixoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_quantidadeAbaixoActionPerformed
        if (jrb_quantidadeAbaixo.isSelected()) {
            jcb_destino.setEnabled(false);
            jrb_ordenarProduto.setEnabled(true);
            jrb_ordenarGrupo.setEnabled(true);
            jcb_grupo.setEnabled(true);
            jl_grupo.setEnabled(true);
            jftf_data.setEnabled(false);
            jftf_data1.setEnabled(false);
            jftf_data.setText("");
            jftf_data1.setText("");

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jrb_quantidadeAbaixoActionPerformed

    private void jftf_dataFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jftf_dataFocusLost
}//GEN-LAST:event_jftf_dataFocusLost

    private void jftf_dataKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jftf_dataKeyPressed
        // TODO add your handling code here:
}//GEN-LAST:event_jftf_dataKeyPressed

    private void jftf_data1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jftf_data1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jftf_data1FocusLost

    private void jftf_data1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jftf_data1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftf_data1KeyPressed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.setVisible(false);
        janelapai.setVisible(true);
        janelapai.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void jcb_destinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_destinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_destinoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new RelatórioGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JButton jb_cancelar;
    private javax.swing.JButton jb_gerar;
    private javax.swing.JComboBox jcb_destino;
    private javax.swing.JComboBox jcb_grupo;
    private javax.swing.JFormattedTextField jftf_data;
    private javax.swing.JFormattedTextField jftf_data1;
    private javax.swing.JLabel jl_grupo;
    private javax.swing.JRadioButton jrb_ideal;
    private javax.swing.JRadioButton jrb_itensEstoque;
    private javax.swing.JRadioButton jrb_listamCompleta;
    private javax.swing.JRadioButton jrb_minima;
    private javax.swing.JRadioButton jrb_movimento;
    private javax.swing.JRadioButton jrb_ordenarGrupo;
    private javax.swing.JRadioButton jrb_ordenarProduto;
    private javax.swing.JRadioButton jrb_quantidadeAbaixo;
    // End of variables declaration//GEN-END:variables
    List<GrupoModel> grupos;

    public void listarGrupo() {
        GrupoDAO grup = new GrupoDAO();
        grupos = grup.listarGrupos();
        mostraGrupos(grupos);

    }

    public void mostraGrupos(List<GrupoModel> grupos) {
        if (grupos.size() == 0) {
            JOptionPane.showMessageDialog(this, "Nenhum grupo encontrado");

        } else {
            for (int i = 0; i < grupos.size(); i++) {//ou i<destino.size() para retornar todos
                GrupoModel grupoModel = new GrupoModel();
                grupoModel.setCod_grupo(grupos.get(i).getCod_grupo());
                grupoModel.setDesc_grupo(grupos.get(i).getDesc_grupo());
                ItemDbGrid hashDbGrid = new ItemDbGrid(grupoModel, grupoModel.getDesc_grupo());
                jcb_grupo.addItem(hashDbGrid);
            }
        }
    }
    List<ArmazemModel> destinos;

    public void listarDestino() {
        DestinoDAO dest = new DestinoDAO();
        destinos = dest.listarDestinos();
        mostraDestinos(destinos);

    }

    public void mostraDestinos(List<ArmazemModel> destinos) {
        if (destinos.size() == 0) {
            JOptionPane.showMessageDialog(this, "Nenhum armazém encontrado");

        } else {
            for (int i = 0; i < destinos.size(); i++) {//ou i<destino.size() para retornar todos
                ArmazemModel destinoModel = new ArmazemModel();
                destinoModel.setCod_destino(destinos.get(i).getCod_destino());
                destinoModel.setDesc_destino(destinos.get(i).getDesc_destino());
                ItemDbGrid hashDbGrid = new ItemDbGrid(destinoModel, destinoModel.getDesc_destino());
                jcb_destino.addItem(hashDbGrid);
            }
        }
    }
}
