/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sig.view;

import br.com.sig.dao.ProdutoDAO;
import br.com.sig.dao.RequisicoesDAO;
import br.com.sig.dao.RequisicoesProdutoDAO;
import br.com.sig.dao.UsuarioDAO;
import br.com.sig.dao.UsuarioRequisitanteDAO;
import br.com.medicalpharm.model.RequisicoesModel;
import br.com.medicalpharm.model.RequisicoesProdutoModel;
import br.com.medicalpharm.model.UsuarioModel;
import br.com.sig.relatorios.Relatorios;
import br.com.sig.util.Data;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author willi
 */
public class RequisicaoListaGUI extends javax.swing.JFrame {

    /**
     * Creates new form RequisicoesLista
     */
    public RequisicaoListaGUI() {
        initComponents();           
        listarRequisicoesAction();
        this.setLocationRelativeTo(null);        
    }
    //DefaultTableModel Jt_requisicoes = new DefaultTableModel(null, new String[]{"Código Requisicao", "Emissão","Estoquista","Status"});
    //DefaultTableModel Jt_requisicoesProduto = new DefaultTableModel(null, new String[]{"Usuario Requisitante","Produto", "Qtd", "Qtd.devolvida", "Saldo"});
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jb_novo3 = new javax.swing.JButton();
        jb_novo2 = new javax.swing.JButton();
        jb_novo = new javax.swing.JButton();
        jb_sair = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jl_pesquisar_destino = new javax.swing.JLabel();
        jb_buscar = new javax.swing.JButton();
        tf_pesquisar_requisicao = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jRadio_aberto = new javax.swing.JRadioButton();
        jRadio_fechado = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jb_novo4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Requisições");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jb_novo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/medicalpharm/image/novo_registro.gif"))); // NOI18N
        jb_novo3.setText("Nova Requisição");
        jb_novo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_novo3ActionPerformed(evt);
            }
        });

        jb_novo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/medicalpharm/image/alterar_registro.gif"))); // NOI18N
        jb_novo2.setText("Editar Requisição");
        jb_novo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_novo2ActionPerformed(evt);
            }
        });

        jb_novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/medicalpharm/image/novo_registro.gif"))); // NOI18N
        jb_novo.setText("Devolução");
        jb_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_novoActionPerformed(evt);
            }
        });

        jb_sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/medicalpharm/image/exit.png"))); // NOI18N
        jb_sair.setText("Sair");
        jb_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_sairActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Consultar Requisição"));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_pesquisar_destino.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jl_pesquisar_destino.setText("Parametro:");
        jPanel1.add(jl_pesquisar_destino, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jb_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/medicalpharm/image/ok.png"))); // NOI18N
        jb_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_buscarActionPerformed1(evt);
            }
        });
        jPanel1.add(jb_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, -1, -1));

        tf_pesquisar_requisicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_pesquisar_requisicaoActionPerformed(evt);
            }
        });
        tf_pesquisar_requisicao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_pesquisar_requisicaoKeyPressed(evt);
            }
        });
        jPanel1.add(tf_pesquisar_requisicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 490, 20));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Código Requisição");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Data");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton3)))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 220, 30));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        buttonGroup2.add(jRadio_aberto);
        jRadio_aberto.setSelected(true);
        jRadio_aberto.setText("Aberto");

        buttonGroup2.add(jRadio_fechado);
        jRadio_fechado.setText("Fechado");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jRadio_aberto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadio_fechado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadio_aberto)
                    .addComponent(jRadio_fechado))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 160, 30));

        jTable1.setUpdateSelectionOnSort(false);
        jTable1.setVerifyInputWhenFocusTarget(false);
        jTable1.setDefaultEditor(Object.class, null);
        jTable1.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e){
                if(e.getClickCount() == 1){
                    listaProdutosRequicao();
                }}});
                jTable1.setModel(new javax.swing.table.DefaultTableModel(
                    new Object [][] {

                    },
                    new String [] {
                        "Código", "Data", "Usuário", "Status"
                    }
                ));
                jScrollPane1.setViewportView(jTable1);
                if (jTable1.getColumnModel().getColumnCount() > 0) {
                    jTable1.getColumnModel().getColumn(0).setMinWidth(70);
                    jTable1.getColumnModel().getColumn(0).setMaxWidth(90);
                    jTable1.getColumnModel().getColumn(1).setMinWidth(80);
                    jTable1.getColumnModel().getColumn(1).setMaxWidth(100);
                    jTable1.getColumnModel().getColumn(3).setMinWidth(70);
                    jTable1.getColumnModel().getColumn(3).setMaxWidth(90);
                }

                jTable2.setUpdateSelectionOnSort(false);
                jTable2.setVerifyInputWhenFocusTarget(false);
                jTable2.setDefaultEditor(Object.class, null);
                jTable2.setModel(new javax.swing.table.DefaultTableModel(
                    new Object [][] {

                    },
                    new String [] {
                        "Usuário Requisitante", "Produto", "Qtd", "Qtd.devolvida", "Saldo"
                    }
                ) {
                    Class[] types = new Class [] {
                        java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
                    };

                    public Class getColumnClass(int columnIndex) {
                        return types [columnIndex];
                    }
                });
                jScrollPane2.setViewportView(jTable2);
                if (jTable2.getColumnModel().getColumnCount() > 0) {
                    jTable2.getColumnModel().getColumn(0).setMinWidth(70);
                    jTable2.getColumnModel().getColumn(0).setMaxWidth(90);
                    jTable2.getColumnModel().getColumn(2).setMinWidth(70);
                    jTable2.getColumnModel().getColumn(2).setMaxWidth(90);
                    jTable2.getColumnModel().getColumn(3).setMinWidth(70);
                    jTable2.getColumnModel().getColumn(3).setMaxWidth(90);
                    jTable2.getColumnModel().getColumn(4).setMinWidth(70);
                    jTable2.getColumnModel().getColumn(4).setMaxWidth(90);
                }

                jb_novo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/medicalpharm/image/printer.png"))); // NOI18N
                jb_novo4.setText("Imprimir");
                jb_novo4.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jb_novo4ActionPerformed(evt);
                    }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jb_novo4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jb_novo3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jb_novo2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jb_novo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jb_sair))
                                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2))
                        .addContainerGap())
                );
                layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jb_sair, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_novo)
                            .addComponent(jb_novo2)
                            .addComponent(jb_novo3)
                            .addComponent(jb_novo4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                        .addContainerGap())
                );

                pack();
            }// </editor-fold>//GEN-END:initComponents

    private void jb_novo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_novo3ActionPerformed
   // if(jTable2.getRowCount() > 1){            
            DefaultTableModel modelo = (DefaultTableModel) jTable2.getModel();
            modelo.setNumRows(0);
     //   }
        RequisicaoNovaGUI abrirTela = new RequisicaoNovaGUI();
            abrirTela.requisicaoLista = this;
            abrirTela.verificarUpdata();
            this.setEnabled(false);
            abrirTela.setVisible(true);        
    }//GEN-LAST:event_jb_novo3ActionPerformed

    private void jb_novo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_novo2ActionPerformed
        if(jTable1.getSelectedRow() != -1){
            RequisicaoNovaGUI abrirTela = new RequisicaoNovaGUI();
            this.setEnabled(false);
            abrirTela.update = true;
            abrirTela.requisicaoLista = this;
            abrirTela.codigo_requisicao = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();               
            abrirTela.verificarUpdata();
            abrirTela.setVisible(true);
        }                
    }//GEN-LAST:event_jb_novo2ActionPerformed

    private void jb_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_novoActionPerformed
        if(jTable1.getSelectedRow() != -1){
            RequisicaoDevolverGUI abrir = new RequisicaoDevolverGUI();
            abrir.codigo = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString().trim();
            abrir.listaProdutosRequicao();
            abrir.janelaPai = this;
            this.setEnabled(false);
            abrir.inicioTabela();
            abrir.setVisible(true);
        }
    }//GEN-LAST:event_jb_novoActionPerformed

    private void jb_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_sairActionPerformed
        setVisible(false);
//        telaPrincipal.setStatusTela(true);
    }//GEN-LAST:event_jb_sairActionPerformed

    private void jb_buscarActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_buscarActionPerformed1
        listarRequisicoesAction();
   
    }//GEN-LAST:event_jb_buscarActionPerformed1

    private void tf_pesquisar_requisicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_pesquisar_requisicaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_pesquisar_requisicaoActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
       setVisible(false);
    }//GEN-LAST:event_formWindowClosed

    private void jb_novo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_novo4ActionPerformed
        if(jTable1.getSelectedRow() != -1){                
            int selectedOption = JOptionPane.showConfirmDialog(this, "Deseja imprimir relatório?", "Atenção", JOptionPane.YES_NO_OPTION);
            if (selectedOption == JOptionPane.YES_NO_OPTION) {
                Relatorios relatorio = new Relatorios();
                int codigo = Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString().trim());
                relatorio.relatorioNovaRequisicao(codigo);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um item da tabela");
        }
    }//GEN-LAST:event_jb_novo4ActionPerformed

    private void tf_pesquisar_requisicaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_pesquisar_requisicaoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) { 
            listarRequisicoesAction();
        } 
    }//GEN-LAST:event_tf_pesquisar_requisicaoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RequisicaoListaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RequisicaoListaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RequisicaoListaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RequisicaoListaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RequisicaoListaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadio_aberto;
    private javax.swing.JRadioButton jRadio_fechado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton jb_buscar;
    private javax.swing.JButton jb_novo;
    private javax.swing.JButton jb_novo2;
    private javax.swing.JButton jb_novo3;
    private javax.swing.JButton jb_novo4;
    private javax.swing.JButton jb_sair;
    private javax.swing.JLabel jl_pesquisar_destino;
    private javax.swing.JTextField tf_pesquisar_requisicao;
    // End of variables declaration//GEN-END:variables

    
    public void listarRequisicoesAction(){
        try{
            if(jRadioButton1.isSelected()){//codigo Requisicao
                listarRequisicoes("codigo Requisicao");       
            }else if(jRadioButton3.isSelected()){//data
                listarRequisicoes("data");
            }
        }catch(Exception ex){
            
        }
    }
    List<RequisicoesModel> requisicoes;
    Data data = new Data();
    public void listarRequisicoes(String opcaoPesquisa){
      //  if(jTable1.getRowCount() > 1){
            DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
            modelo.setNumRows(0);
     //   }                
        RequisicoesProdutoDAO d = new RequisicoesProdutoDAO();
        RequisicoesDAO requi = new RequisicoesDAO();        
        requisicoes = requi.listarRequisicoes(tf_pesquisar_requisicao.getText(),opcaoPesquisa);        
        UsuarioDAO buscar = new UsuarioDAO();        
        DefaultTableModel row = (DefaultTableModel) jTable1.getModel();        
        for (int i = 0; i < requisicoes.size(); i++) {            
            String usuarioEstoquista = buscarUsuarioCodigo(i);            
            String status = requi.statusRequisicao(requisicoes.get(i).getCodigo_requisicao().toString());
            if(jRadio_aberto.isSelected() && status.equals("Aberto")){
                row.addRow(new Object[]{requisicoes.get(i).getCodigo_requisicao(),data.inverterData(requisicoes.get(i).getData_emissao().toString(),"sql"),usuarioEstoquista,status});            
            }else if(jRadio_fechado.isSelected() && status.equals("Fechado")){
                row.addRow(new Object[]{requisicoes.get(i).getCodigo_requisicao(),data.inverterData(requisicoes.get(i).getData_emissao().toString(),"sql"),usuarioEstoquista,status});            
            }
        }
    }
    private String buscarUsuarioCodigo(int i){
        List<UsuarioModel> lista = new ArrayList();
        UsuarioDAO buscar = new UsuarioDAO();
        lista = buscar.listarUsuarioCodigo(requisicoes.get(i).getUsuario_estoquista());
        return lista.get(0).getNome_usuario();        
    }

    public void listaProdutosRequicao(){  
      //  if(jTable2.getRowCount() > 1){            
            DefaultTableModel modelo = (DefaultTableModel) jTable2.getModel();
            modelo.setNumRows(0);
      //  }     
        

        RequisicoesProdutoDAO d = new RequisicoesProdutoDAO();
        ArrayList<RequisicoesProdutoModel> itens = d.buscarRequisicaoPorCodigo(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString().trim());
        
        DefaultTableModel row = (DefaultTableModel) jTable2.getModel();
    
        for (int i = 0; i < itens.size(); i++) {        
                
            row.addRow(new Object[]{buscarRequisitanteCodigo(itens.get(i).getCodigoRequisicao()),buscarProdutoCodigo(itens.get(i).getProduto()),itens.get(i).getQtd(),itens.get(i).getQtdDevolvida(),itens.get(i).getSaldo()});
            
        }
    }
    
    private String buscarProdutoCodigo(String codigo){
        ProdutoDAO buscar = new ProdutoDAO();
        return buscar.listarProdutoCodigo(codigo);
    }
    
    private String buscarRequisitanteCodigo(int cod){
        UsuarioRequisitanteDAO buscar = new UsuarioRequisitanteDAO();
        return buscar.buscarRequisitanteCodigo(cod);
    }
    
        public boolean verificarProdutoRepetidoNome(String produto){
        DefaultTableModel row = (DefaultTableModel) jTable2.getModel();      
        for (int i = 0; i < row.getRowCount(); i++) {      
            if(row.getValueAt(i, 1) != null){
                if(row.getValueAt(i, 1).equals(produto) ){
                    return false;
                }         
            }else{
                return false;
            }
        }
        return true;
    }
}
