package br.com.sig.view;

import br.com.sig.dao.ProdutoDAO;
import br.com.medicalpharm.model.ProdutoModel;
import br.com.medicalpharm.model.RequisicoesModel;
import br.com.medicalpharm.model.UsuarioModel;
import br.com.sig.relatorios.Relatorios;
import br.com.sig.util.Backup;
import br.com.sig.util.Data;
import br.com.sig.util.ItemDbGrid;
import br.com.sig.util.Restaurar;
import java.awt.Toolkit;
import java.text.ParseException;
import javax.swing.table.DefaultTableModel;
import java.io.IOException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.UIManager;

public class TelaPrincipal extends javax.swing.JFrame implements TelaPrincipal_Interface {

    LoginGUI janelaPai;
    LoginGUI janelaLogin;
    public UsuarioModel usuario;
    public String usuarioNome;
    public Integer codUsuario;
    public String login;
    public String permissao;

    public TelaPrincipal() {
        initComponents();
        //setIconFrame();
        jPanel1.setVisible(false);
        jPanel4.setVisible(false);
        Data mostraData = new Data();
        mostraData.le_data();
        jlabel_data.setText("Data: " + mostraData.dia + "/" + mostraData.mes + "/" + mostraData.ano);
        mostraData.le_hora();
        jlabel_hora.setText("Hora: " + mostraData.hora);
        lookandField();
        timer1.start();
        vencidos();        
        estoqueMinimo();
        //setUsuario();

        
    }

    public void setJanelaPai(LoginGUI janelaPai) {
        jlabel_usuario.setText("Usuário: " + janelaPai.usuarioNome);
        RequisicoesModel.usuarioNome1 = janelaPai.usuarioNome;
        janelaPai = janelaPai;
        usuarioNome = janelaPai.usuarioNome;
        codUsuario = janelaPai.codUsuário;
        login = janelaPai.login;
        permissao = janelaPai.permissao;
        //setUsuario();
        //JOptionPane.showMessageDialog(null, permissao);


        //  JOptionPane.showMessageDialog(null,codUsuario);
    }

    public void setUsuario() {
        usuario.setCod_usuario(codUsuario);
        usuario.setNome_usuário(usuarioNome);
        usuario.setPermissao(permissao);
        usuario.setLogin(login);
        JOptionPane.showMessageDialog(null, usuario.getCod_usuario() + usuario.getNome_usuario() + usuario.getPermissao());
    }
    String seta_look;

    public void lookandField() {
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            // UIManager.setLookAndFeel("com.sun.java.swing.plaf.smoothmetal.SmoothmetalLookAndAndFeel");
            //UIManager.setLookAndFeel("com.birosoft.liquid.LiquidLookAndFeel");
            //UIManager.setLookAndFeel(seta_look);
            SwingUtilities.updateComponentTreeUI(this);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timer1 = new org.netbeans.examples.lib.timerbean.Timer();
        jFrame1 = new javax.swing.JFrame();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuBar5 = new javax.swing.JMenuBar();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenuBar6 = new javax.swing.JMenuBar();
        jMenu11 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenuBar7 = new javax.swing.JMenuBar();
        jMenu13 = new javax.swing.JMenu();
        jMenu14 = new javax.swing.JMenu();
        label_data = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton15 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jb_usuario = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jb_entrada = new javax.swing.JButton();
        jb_saida = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jb_saidaArmazem = new javax.swing.JButton();
        jb_ajuste = new javax.swing.JButton();
        jb_ajuste1 = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        jlabel_data = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlabel_hora = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jlabel_usuario = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_minimo = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jl_minimo = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jt_ideal = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jl_quantidade = new javax.swing.JLabel();
        jMB_Cadastro = new javax.swing.JMenuBar();
        menu_cadastros = new javax.swing.JMenu();
        jmi_produto = new javax.swing.JMenuItem();
        jmi_fornecedor = new javax.swing.JMenuItem();
        jmi_unidade = new javax.swing.JMenuItem();
        jmi_grupo = new javax.swing.JMenuItem();
        jmi_usuarios = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jmi_destino = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuitem_sair = new javax.swing.JMenuItem();
        menu_movimentos = new javax.swing.JMenu();
        jmi_entrada = new javax.swing.JMenuItem();
        jmi_saida = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jmi_ajuste = new javax.swing.JMenuItem();
        menu_relatórios = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        menuitem_vencidos = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        menu_relatórios1 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jmi_backup = new javax.swing.JMenuItem();
        jmi_recover = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menu_relatórios2 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();

        timer1.addTimerListener(new org.netbeans.examples.lib.timerbean.TimerListener() {
            public void onTime(java.awt.event.ActionEvent evt) {
                timer1OnTime(evt);
            }
        });

        jFrame1.setName("jFrame1"); // NOI18N

        jMenuBar1.setName("jMenuBar1"); // NOI18N

        jMenu1.setText("File");
        jMenu1.setName("jMenu1"); // NOI18N
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenu2.setName("jMenu2"); // NOI18N
        jMenuBar1.add(jMenu2);

        jMenuBar2.setName("jMenuBar2"); // NOI18N

        jMenu3.setText("File");
        jMenu3.setName("jMenu3"); // NOI18N
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenu4.setName("jMenu4"); // NOI18N
        jMenuBar2.add(jMenu4);

        jMenuBar3.setName("jMenuBar3"); // NOI18N

        jMenu5.setText("File");
        jMenu5.setName("jMenu5"); // NOI18N
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenu6.setName("jMenu6"); // NOI18N
        jMenuBar3.add(jMenu6);

        jMenuBar4.setName("jMenuBar4"); // NOI18N

        jMenu7.setText("File");
        jMenu7.setName("jMenu7"); // NOI18N
        jMenuBar4.add(jMenu7);

        jMenu8.setText("Edit");
        jMenu8.setName("jMenu8"); // NOI18N
        jMenuBar4.add(jMenu8);

        jMenuBar5.setName("jMenuBar5"); // NOI18N

        jMenu9.setText("File");
        jMenu9.setName("jMenu9"); // NOI18N
        jMenuBar5.add(jMenu9);

        jMenu10.setText("Edit");
        jMenu10.setName("jMenu10"); // NOI18N
        jMenuBar5.add(jMenu10);

        jMenuBar6.setName("jMenuBar6"); // NOI18N

        jMenu11.setText("File");
        jMenu11.setName("jMenu11"); // NOI18N
        jMenuBar6.add(jMenu11);

        jMenu12.setText("Edit");
        jMenu12.setName("jMenu12"); // NOI18N
        jMenuBar6.add(jMenu12);

        jMenuBar7.setName("jMenuBar7"); // NOI18N

        jMenu13.setText("File");
        jMenu13.setName("jMenu13"); // NOI18N
        jMenuBar7.add(jMenu13);

        jMenu14.setText("Edit");
        jMenu14.setName("jMenu14"); // NOI18N
        jMenuBar7.add(jMenu14);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de gerenciamento");
        setExtendedState(MAXIMIZED_BOTH);
        setFocusable(false);
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.TOOLKIT_EXCLUDE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_data.setName("label_data"); // NOI18N
        getContentPane().add(label_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(1243, 632, -1, -1));

        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/medicalpharm/image/product2.png"))); // NOI18N
        jButton15.setToolTipText("Produto"); // NOI18N
        jButton15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 66, 57));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/medicalpharm/image/factory.png"))); // NOI18N
        jButton10.setToolTipText("Fornecedor");
        jButton10.setName("jButton10"); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 66, 57));

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/medicalpharm/image/grupo.png"))); // NOI18N
        jButton12.setToolTipText("Grupo");
        jButton12.setName("jButton12"); // NOI18N
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton12MouseReleased(evt);
            }
        });
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 66, 57));

        jb_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/medicalpharm/image/users2.png"))); // NOI18N
        jb_usuario.setToolTipText("Usuário");
        jb_usuario.setName("jb_usuario"); // NOI18N
        jb_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_usuarioActionPerformed(evt);
            }
        });
        jPanel2.add(jb_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 66, 57));

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/medicalpharm/image/icone-armazens-gerais.png"))); // NOI18N
        jButton14.setToolTipText("Almoxarifado");
        jButton14.setName("jButton14"); // NOI18N
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 66, 57));

        jb_entrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/medicalpharm/image/shoppingcart_full.png"))); // NOI18N
        jb_entrada.setToolTipText("Entrada de produtos");
        jb_entrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_entradaActionPerformed(evt);
            }
        });
        jPanel2.add(jb_entrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 66, 57));

        jb_saida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/medicalpharm/image/shoppingbasket_full.png"))); // NOI18N
        jb_saida.setToolTipText("Saída de estoque principal");
        jb_saida.setName("jb_saida"); // NOI18N
        jb_saida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_saidaActionPerformed(evt);
            }
        });
        jPanel2.add(jb_saida, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 66, 57));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/medicalpharm/image/exit.png"))); // NOI18N
        jButton7.setToolTipText("Sair");
        jButton7.setName("jButton7"); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 66, 57));

        jb_saidaArmazem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/medicalpharm/image/shoppingbasket_delete.png"))); // NOI18N
        jb_saidaArmazem.setToolTipText("Saída de estoque por almoxarifado ");
        jb_saidaArmazem.setName("jb_saidaArmazem"); // NOI18N
        jb_saidaArmazem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_saidaArmazemActionPerformed(evt);
            }
        });
        jPanel2.add(jb_saidaArmazem, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 66, 57));

        jb_ajuste.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/medicalpharm/image/registry.png"))); // NOI18N
        jb_ajuste.setToolTipText("Ajustar estoque");
        jb_ajuste.setName("jb_ajuste"); // NOI18N
        jb_ajuste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_ajusteActionPerformed(evt);
            }
        });
        jPanel2.add(jb_ajuste, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 66, 57));

        jb_ajuste1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/medicalpharm/image/saida.png"))); // NOI18N
        jb_ajuste1.setToolTipText("Requisições");
        jb_ajuste1.setName("jb_ajuste1"); // NOI18N
        jb_ajuste1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_ajuste1ActionPerformed(evt);
            }
        });
        jPanel2.add(jb_ajuste1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 66, 57));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 80));

        jToolBar1.setRollover(true);
        jToolBar1.setName("jToolBar1"); // NOI18N

        jlabel_data.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jlabel_data.setText("Data:");
        jlabel_data.setName("jlabel_data"); // NOI18N
        jToolBar1.add(jlabel_data);

        jLabel2.setText("                               ");
        jLabel2.setName("jLabel2"); // NOI18N
        jToolBar1.add(jLabel2);

        jlabel_hora.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jlabel_hora.setText("Hora:");
        jlabel_hora.setName("jlabel_hora"); // NOI18N
        jToolBar1.add(jlabel_hora);

        jLabel1.setText("                               ");
        jLabel1.setName("jLabel1"); // NOI18N
        jToolBar1.add(jLabel1);

        jlabel_usuario.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jlabel_usuario.setText("Usuário: ");
        jlabel_usuario.setName("jlabel_usuario"); // NOI18N
        jToolBar1.add(jlabel_usuario);

        jLabel4.setText("                                                                                                                                                                ");
        jLabel4.setName("jLabel4"); // NOI18N
        jToolBar1.add(jLabel4);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel3.setText("Desenvolvido por Alencar Santos Buriti Júnior                                             ");
        jLabel3.setName("jLabel3"); // NOI18N
        jToolBar1.add(jLabel3);

        getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, 1340, 25));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/medicalpharm/image/SistemaSey.png"))); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 680, 280));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Estoque Mínimo atingido"));
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jt_minimo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto", "Nome comercial", "Estoque Mínimo", "Quantidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jt_minimo.setName("jt_minimo"); // NOI18N
        jt_minimo.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jt_minimo);
        if (jt_minimo.getColumnModel().getColumnCount() > 0) {
            jt_minimo.getColumnModel().getColumn(2).setPreferredWidth(30);
            jt_minimo.getColumnModel().getColumn(3).setPreferredWidth(30);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 100));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/medicalpharm/image/printer.png"))); // NOI18N
        jButton3.setText("Imprimir");
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Estoque Ideal atingido"));
        jPanel3.setName("jPanel3"); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto", "Concentração", "Estoque Ideal", "Quantidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setName("jTable2"); // NOI18N
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(2).setPreferredWidth(30);
            jTable2.getColumnModel().getColumn(3).setPreferredWidth(30);
        }

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 100));

        jButton4.setText("Imprimir");
        jButton4.setName("jButton4"); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 500, 180));

        jl_minimo.setText("jLabel6");
        jl_minimo.setName("jl_minimo"); // NOI18N
        jPanel1.add(jl_minimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 460, 500, 190));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Estoque central vencido"));
        jPanel4.setName("jPanel4"); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        jt_ideal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto", "Nome comercial", "Vencimento", "Quant"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jt_ideal.setName("jt_ideal"); // NOI18N
        jt_ideal.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jt_ideal);
        if (jt_ideal.getColumnModel().getColumnCount() > 0) {
            jt_ideal.getColumnModel().getColumn(0).setPreferredWidth(150);
            jt_ideal.getColumnModel().getColumn(1).setPreferredWidth(150);
            jt_ideal.getColumnModel().getColumn(2).setPreferredWidth(40);
            jt_ideal.getColumnModel().getColumn(3).setPreferredWidth(20);
        }

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 470, 100));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/medicalpharm/image/printer.png"))); // NOI18N
        jButton5.setText("Imprimir");
        jButton5.setName("jButton5"); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, -1, -1));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Estoque Ideal atingido"));
        jPanel5.setName("jPanel5"); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane4.setName("jScrollPane4"); // NOI18N

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto", "Concentração", "Estoque Ideal", "Quantidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable4.setName("jTable4"); // NOI18N
        jTable4.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(jTable4);
        if (jTable4.getColumnModel().getColumnCount() > 0) {
            jTable4.getColumnModel().getColumn(2).setPreferredWidth(30);
            jTable4.getColumnModel().getColumn(3).setPreferredWidth(30);
        }

        jPanel5.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 100));

        jButton6.setText("Imprimir");
        jButton6.setName("jButton6"); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, -1, -1));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 500, 180));

        jl_quantidade.setText("   ");
        jl_quantidade.setName("jl_quantidade"); // NOI18N
        jPanel4.add(jl_quantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 520, 190));

        jMB_Cadastro.setName("jMB_Cadastro"); // NOI18N

        menu_cadastros.setMnemonic('C');
        menu_cadastros.setText("Cadastro");
        menu_cadastros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_cadastrosActionPerformed(evt);
            }
        });

        jmi_produto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/medicalpharm/image/product2.png"))); // NOI18N
        jmi_produto.setMnemonic('P');
        jmi_produto.setText("Produto");
        jmi_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_produtoActionPerformed(evt);
            }
        });
        menu_cadastros.add(jmi_produto);

        jmi_fornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/medicalpharm/image/factory.png"))); // NOI18N
        jmi_fornecedor.setMnemonic('F');
        jmi_fornecedor.setText("Fornecedor");
        jmi_fornecedor.setName("jmi_fornecedor"); // NOI18N
        jmi_fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_fornecedorActionPerformed(evt);
            }
        });
        jmi_fornecedor.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jmi_fornecedorAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        menu_cadastros.add(jmi_fornecedor);

        jmi_unidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/medicalpharm/image/box_closed.png"))); // NOI18N
        jmi_unidade.setText("Unidade");
        jmi_unidade.setName("jmi_unidade"); // NOI18N
        jmi_unidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_unidadeActionPerformed(evt);
            }
        });
        menu_cadastros.add(jmi_unidade);

        jmi_grupo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/medicalpharm/image/grupo.png"))); // NOI18N
        jmi_grupo.setText("Grupo");
        jmi_grupo.setName("jmi_grupo"); // NOI18N
        jmi_grupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_grupoActionPerformed(evt);
            }
        });
        menu_cadastros.add(jmi_grupo);

        jmi_usuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/medicalpharm/image/users2.png"))); // NOI18N
        jmi_usuarios.setMnemonic('U');
        jmi_usuarios.setText("Usuários");
        jmi_usuarios.setName("jmi_usuarios"); // NOI18N
        jmi_usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmi_usuariosMouseClicked(evt);
            }
        });
        jmi_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_usuariosActionPerformed(evt);
            }
        });
        menu_cadastros.add(jmi_usuarios);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/medicalpharm/image/users_back.png"))); // NOI18N
        jMenuItem2.setText("Requisitantes");
        jMenuItem2.setName("jMenuItem2"); // NOI18N
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menu_cadastros.add(jMenuItem2);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/medicalpharm/image/template_source.png"))); // NOI18N
        jMenuItem4.setText("Veiculos");
        jMenuItem4.setName("jMenuItem4"); // NOI18N
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        menu_cadastros.add(jMenuItem4);

        jmi_destino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/medicalpharm/image/icone-armazens-gerais.png"))); // NOI18N
        jmi_destino.setText("Almoxarifado");
        jmi_destino.setName("jmi_destino"); // NOI18N
        jmi_destino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_destinoActionPerformed1(evt);
            }
        });
        menu_cadastros.add(jmi_destino);

        jSeparator2.setName("jSeparator2"); // NOI18N
        menu_cadastros.add(jSeparator2);

        menuitem_sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/medicalpharm/image/exit.png"))); // NOI18N
        menuitem_sair.setText("Sair");
        menuitem_sair.setName("menuitem_sair"); // NOI18N
        menuitem_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitem_sairActionPerformed(evt);
            }
        });
        menu_cadastros.add(menuitem_sair);

        jMB_Cadastro.add(menu_cadastros);

        menu_movimentos.setMnemonic('M');
        menu_movimentos.setText("Movimento");
        menu_movimentos.setName("menu_movimentos"); // NOI18N

        jmi_entrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/medicalpharm/image/shoppingcart_full.png"))); // NOI18N
        jmi_entrada.setText("Entrada de produtos");
        jmi_entrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_entradaActionPerformed1(evt);
            }
        });
        menu_movimentos.add(jmi_entrada);

        jmi_saida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/medicalpharm/image/shoppingbasket_full.png"))); // NOI18N
        jmi_saida.setText("Saída de estoque principal");
        jmi_saida.setName("jmi_saida"); // NOI18N
        jmi_saida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_saidaActionPerformed(evt);
            }
        });
        menu_movimentos.add(jmi_saida);

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/medicalpharm/image/shoppingbasket_delete.png"))); // NOI18N
        jMenuItem7.setText("Saída de estoque por almoxarifado ");
        jMenuItem7.setName("jMenuItem7"); // NOI18N
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed1(evt);
            }
        });
        menu_movimentos.add(jMenuItem7);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/medicalpharm/image/saida.png"))); // NOI18N
        jMenuItem3.setText("Requisições");
        jMenuItem3.setToolTipText("");
        jMenuItem3.setName("jMenuItem3"); // NOI18N
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menu_movimentos.add(jMenuItem3);

        jmi_ajuste.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/medicalpharm/image/registry.png"))); // NOI18N
        jmi_ajuste.setText("Ajustar Estoque");
        jmi_ajuste.setName("jmi_ajuste"); // NOI18N
        jmi_ajuste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_ajusteActionPerformed(evt);
            }
        });
        menu_movimentos.add(jmi_ajuste);

        jMB_Cadastro.add(menu_movimentos);

        menu_relatórios.setMnemonic('R');
        menu_relatórios.setText("Relatório");
        menu_relatórios.setName("menu_relatórios"); // NOI18N
        menu_relatórios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_relatóriosActionPerformed(evt);
            }
        });

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/medicalpharm/image/relatório.gif"))); // NOI18N
        jMenuItem6.setText("Estoque");
        jMenuItem6.setName("jMenuItem6"); // NOI18N
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        menu_relatórios.add(jMenuItem6);

        menuitem_vencidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/medicalpharm/image/index_replace.png"))); // NOI18N
        menuitem_vencidos.setText("Almoxarifado");
        menuitem_vencidos.setName("menuitem_vencidos"); // NOI18N
        menuitem_vencidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitem_vencidosActionPerformed(evt);
            }
        });
        menu_relatórios.add(menuitem_vencidos);

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/medicalpharm/image/template_source.png"))); // NOI18N
        jMenuItem8.setText("A vencer");
        jMenuItem8.setName("jMenuItem8"); // NOI18N
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        menu_relatórios.add(jMenuItem8);

        jMB_Cadastro.add(menu_relatórios);

        menu_relatórios1.setMnemonic('R');
        menu_relatórios1.setText("Utilitários");
        menu_relatórios1.setName("menu_relatórios1"); // NOI18N
        menu_relatórios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_relatórios1ActionPerformed(evt);
            }
        });

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/medicalpharm/image/calculator.png"))); // NOI18N
        jMenuItem9.setText("Calculadora ");
        jMenuItem9.setName("jMenuItem9"); // NOI18N
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed1(evt);
            }
        });
        menu_relatórios1.add(jMenuItem9);

        jmi_backup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/medicalpharm/image/save_all.png"))); // NOI18N
        jmi_backup.setText("Backup");
        jmi_backup.setName("jmi_backup"); // NOI18N
        jmi_backup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_backupActionPerformed(evt);
            }
        });
        menu_relatórios1.add(jmi_backup);

        jmi_recover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/medicalpharm/image/revert.png"))); // NOI18N
        jmi_recover.setText("Restaurar Backup");
        jmi_recover.setName("jmi_recover"); // NOI18N
        jmi_recover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_recoverActionPerformed(evt);
            }
        });
        menu_relatórios1.add(jmi_recover);

        jSeparator3.setName("jSeparator3"); // NOI18N
        menu_relatórios1.add(jSeparator3);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/medicalpharm/image/users_back.png"))); // NOI18N
        jMenuItem1.setText("Trocar de usuário");
        jMenuItem1.setName("jMenuItem1"); // NOI18N
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menu_relatórios1.add(jMenuItem1);

        jSeparator1.setName("jSeparator1"); // NOI18N
        menu_relatórios1.add(jSeparator1);

        jMB_Cadastro.add(menu_relatórios1);

        menu_relatórios2.setMnemonic('R');
        menu_relatórios2.setText("Ajuda");
        menu_relatórios2.setName("menu_relatórios2"); // NOI18N
        menu_relatórios2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_relatórios2ActionPerformed(evt);
            }
        });

        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/medicalpharm/image/help_index.png"))); // NOI18N
        jMenuItem10.setText("Help!");
        jMenuItem10.setName("jMenuItem10"); // NOI18N
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        menu_relatórios2.add(jMenuItem10);

        jMB_Cadastro.add(menu_relatórios2);

        setJMenuBar(jMB_Cadastro);

        setSize(new java.awt.Dimension(1233, 745));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuitem_entradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitem_entradaActionPerformed
        EntradaCadastraGUI entradaGUI;
        try {
            entradaGUI = new EntradaCadastraGUI();
            entradaGUI.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_menuitem_entradaActionPerformed

    private void jb_entradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_entradaActionPerformed
        if(entrada == false){
            entradaGUI = new EntradaGUI();
            entradaGUI.setVisible(true);
            entradaGUI.setTelaPrincipal(this);
            entradaGUI.setJanelaPai(this); 
            entrada = true;
        } else {
            entradaGUI.setVisible(true);
        }

      //  setStatusTela(false);

    }//GEN-LAST:event_jb_entradaActionPerformed
    boolean saida = false;
    SaidaGUI saidaGUI;
    private void jb_saidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_saidaActionPerformed
        if(saida == false){
            saidaGUI = new SaidaGUI();
            saidaGUI.setTelaPrincipal(this);
            saidaGUI.setVisible(true);
            saida = true;
        } else {
            saidaGUI.setVisible(true);
        }
      //  setStatusTela(false);
    }//GEN-LAST:event_jb_saidaActionPerformed

    private void jmi_saidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_saidaActionPerformed
        if(saida == false){
            saidaGUI = new SaidaGUI();
            saidaGUI.setTelaPrincipal(this);
            saidaGUI.setVisible(true);
            saida = true;
        } else {
            saidaGUI.setVisible(true);
        }
     //   setStatusTela(false);
    }//GEN-LAST:event_jmi_saidaActionPerformed

    private void jmi_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_produtoActionPerformed
        ProdutoGUI produtoGUI = new ProdutoGUI();
        produtoGUI.setTelaPrincipal(this);
        produtoGUI.setTela(permissao);
        produtoGUI.setVisible(true);
        setStatusTela(false);
    }//GEN-LAST:event_jmi_produtoActionPerformed

        boolean entrada = false;
        EntradaGUI entradaGUI;
    private void jmi_entradaActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_entradaActionPerformed1
        if(entrada == false){
            entradaGUI = new EntradaGUI();
            entradaGUI.setVisible(true);
            entradaGUI.setTelaPrincipal(this);
            entradaGUI.setJanelaPai(this); 
            entrada = true;
        } else {
            entradaGUI.setVisible(true);
        }

        //    setStatusTela(false);

    }//GEN-LAST:event_jmi_entradaActionPerformed1

    private void menu_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_sairActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_sairActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        EntradaGUI entradaGUI = new EntradaGUI();
        entradaGUI.setVisible(true);
      //  setStatusTela(false);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void menu_cadastrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_cadastrosActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_menu_cadastrosActionPerformed

    private void menuitem_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitem_sairActionPerformed
        System.exit(0);
        // TODO add your handling code here:
}//GEN-LAST:event_menuitem_sairActionPerformed

    private void jmi_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_usuariosActionPerformed
        UsuárioGUI usuarioGUI = new UsuárioGUI();
        usuarioGUI.setTelaPrincipal(this);
        usuarioGUI.setVisible(true);
        setStatusTela(false);
}//GEN-LAST:event_jmi_usuariosActionPerformed

    private void jmi_usuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmi_usuariosMouseClicked
}//GEN-LAST:event_jmi_usuariosMouseClicked

    private void jmi_grupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_grupoActionPerformed
        GrupoGUI grupoGUI = new GrupoGUI();
        grupoGUI.setTelaPrincipal(this);
        grupoGUI.setVisible(true);
        grupoGUI.setTela(permissao);
        setStatusTela(false);
}//GEN-LAST:event_jmi_grupoActionPerformed

    private void jmi_unidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_unidadeActionPerformed
        UnidadeGUI unidadeGUI = new UnidadeGUI();
        unidadeGUI.setTelaPrincipal(this);
        unidadeGUI.setVisible(true);
        unidadeGUI.setTela(permissao);
        setStatusTela(false);
}//GEN-LAST:event_jmi_unidadeActionPerformed

    private void jmi_fornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_fornecedorActionPerformed
        FornecedorGUI fornecedorGUI = new FornecedorGUI();
        fornecedorGUI.setTelaPrincipal(this);
        fornecedorGUI.setVisible(true);
        fornecedorGUI.setTela(permissao);
        setStatusTela(false);
    }//GEN-LAST:event_jmi_fornecedorActionPerformed

    private void jmi_destinoActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_destinoActionPerformed1
        DestinoGUI destinoGUI = new DestinoGUI();
        destinoGUI.setTelaPrincipal(this);
        destinoGUI.setVisible(true);
        destinoGUI.setTela(permissao);
        setStatusTela(false);
    }//GEN-LAST:event_jmi_destinoActionPerformed1

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void jmi_fornecedorAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jmi_fornecedorAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_fornecedorAncestorAdded

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        FornecedorGUI fornecedorGUI = new FornecedorGUI();
        fornecedorGUI.setTelaPrincipal(this);
        fornecedorGUI.setVisible(true);
        fornecedorGUI.setTela(permissao);
        setStatusTela(false);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        GrupoGUI grupoGUI = new GrupoGUI();
        grupoGUI.setTelaPrincipal(this);
        grupoGUI.setVisible(true);
        grupoGUI.setTela(permissao);
        setStatusTela(false);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jb_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_usuarioActionPerformed
        UsuárioGUI usuarioGUI = new UsuárioGUI();
        usuarioGUI.setTelaPrincipal(this);
        usuarioGUI.setVisible(true);
        setStatusTela(false);
    }//GEN-LAST:event_jb_usuarioActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        DestinoGUI destinoGUI = new DestinoGUI();
        destinoGUI.setTelaPrincipal(this);
        destinoGUI.setVisible(true);
        destinoGUI.setTela(permissao);
        setStatusTela(false);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        ProdutoGUI produtoGUI = new ProdutoGUI();
        produtoGUI.setTelaPrincipal(this);
        produtoGUI.janelapai = this;
        produtoGUI.setTela(permissao);
        produtoGUI.setVisible(true);
        setStatusTela(false);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void timer1OnTime(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timer1OnTime
        Data mostraData = new Data();
        mostraData.le_hora();
        jlabel_hora.setText("Hora: " + mostraData.hora);

    }//GEN-LAST:event_timer1OnTime

    private void jButton12MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12MouseReleased

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jmi_ajusteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_ajusteActionPerformed
        if(ajuste == false){
            ajusteGUI = new AjusteGUI();
            ajusteGUI.setTelaPrincipal(this);
            ajusteGUI.setUsuario(this);
            ajusteGUI.setVisible(true);
            ajuste = true;
            
        } else {
            ajusteGUI.setVisible(true);
        }
    
          //  setStatusTela(false);
  
    }//GEN-LAST:event_jmi_ajusteActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        ArmazemGUI armazem = new ArmazemGUI();
        armazem.setTelaPrincipal(this);
        armazem.setVisible(true);
       // setStatusTela(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void menu_relatóriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_relatóriosActionPerformed
        RelatórioVencidosGUI relatorioVencidos = new RelatórioVencidosGUI();
        relatorioVencidos.setTelaPrincipal(this);
        relatorioVencidos.janelapai = this;
        relatorioVencidos.setVisible(true);
        setStatusTela(false);
        // TODO add your handling code here:
}//GEN-LAST:event_menu_relatóriosActionPerformed

    private void menuitem_vencidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitem_vencidosActionPerformed
        RelatórioArmazemGUI relatorioArmazem = new RelatórioArmazemGUI();
        relatorioArmazem.setTelaPrincipal(this);
        relatorioArmazem.janelapai = this;
        relatorioArmazem.setVisible(true);
        setStatusTela(false);
    }//GEN-LAST:event_menuitem_vencidosActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        RelatórioGUI relatorio = new RelatórioGUI();
        relatorio.setTelaPrincipal(this);
        relatorio.janelapai = this;
        relatorio.setVisible(true);
        setStatusTela(false);
        // TODO add your handling code here:
}//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        RelatórioVencidosGUI relatorioVencidos = new RelatórioVencidosGUI();
        relatorioVencidos.setTelaPrincipal(this);
        relatorioVencidos.janelapai = this;
        relatorioVencidos.setVisible(true);
      //  setStatusTela(false);       // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void menu_relatórios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_relatórios1ActionPerformed
        System.exit(0);
        LoginGUI login = new LoginGUI();
        login.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_relatórios1ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        try {
            Runtime.getRuntime().exec("calc");
        } catch (IOException exc) {
            exc.printStackTrace();
        }        // TODO add your handling code here:
}//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void menu_relatórios2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_relatórios2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_relatórios2ActionPerformed

    private void jb_saidaArmazemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_saidaArmazemActionPerformed
     if(armazemGUI == false){
            armazem = new ArmazemGUI();
            armazem.setTelaPrincipal(this);
            armazem.setVisible(true);
            armazemGUI =true;
        } else {
            armazem.setVisible(true);
        }
      //  setStatusTela(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_saidaArmazemActionPerformed
    boolean ajuste = false;
    AjusteGUI ajusteGUI;
    private void jb_ajusteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_ajusteActionPerformed
        if(ajuste == false){
            ajusteGUI = new AjusteGUI();
            ajusteGUI.setTelaPrincipal(this);
            ajusteGUI.setUsuario(this);
            ajusteGUI.setVisible(true);
            ajuste = true;
            
        } else {
            ajusteGUI.setVisible(true);
        }
    
            //setStatusTela(false);
          // TODO add your handling code here:
    }//GEN-LAST:event_jb_ajusteActionPerformed

        ArmazemGUI armazem;
        boolean armazemGUI = false;
    private void jMenuItem7ActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed1
        if(armazemGUI == false){
            armazem = new ArmazemGUI();
            armazem.setTelaPrincipal(this);
            armazem.setVisible(true);
            armazemGUI =true;
        } else {
            armazem.setVisible(true);
        }
       // setStatusTela(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed1

    private void jMenuItem9ActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed1
        try {
            Runtime.getRuntime().exec("calc");
        } catch (IOException exc) {
            exc.printStackTrace();
        }          // TODO add your handling code here:
}//GEN-LAST:event_jMenuItem9ActionPerformed1

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        setVisible(false);
        LoginGUI login = new LoginGUI();
        login.show();
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

private void jmi_backupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_backupActionPerformed
    Backup backup = new Backup();

    backup.setVisible(true);
    // TODO add your handling code here:
}//GEN-LAST:event_jmi_backupActionPerformed

private void jmi_recoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_recoverActionPerformed

    Restaurar recover = new Restaurar();
    recover.setVisible(true);

    // TODO add your handling code here:
}//GEN-LAST:event_jmi_recoverActionPerformed
    RequisicaoListaGUI requisicaoLista;
    private void jb_ajuste1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_ajuste1ActionPerformed
        requisicaoLista = new RequisicaoListaGUI();
        requisicaoLista.setVisible(true);
    }//GEN-LAST:event_jb_ajuste1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        RequisitanteGerenciarGUI abrir = new RequisitanteGerenciarGUI();
        abrir.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        requisicaoLista = new RequisicaoListaGUI();
        requisicaoLista.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        VeiculoConsultarGUI abrir = new VeiculoConsultarGUI();
        abrir.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Relatorios relatorio = new Relatorios();
        relatorio.setEstoqueMinimoProduto();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Relatorios relatorio = new Relatorios();
        //relatorio.setVencidos();
       // relatorio.relatorioRequisicoes();
//        relatorio.relatorioEdicaoRequisicao(1,new java.sql.Date(new java.util.Date().getTime()));
        relatorio.relatorioEdicaoRequisicao(1,new java.sql.Date(new java.util.Date().getTime()));
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TelaPrincipal().setVisible(true);

            }
        });

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMB_Cadastro;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuBar jMenuBar5;
    private javax.swing.JMenuBar jMenuBar6;
    private javax.swing.JMenuBar jMenuBar7;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton jb_ajuste;
    private javax.swing.JButton jb_ajuste1;
    private javax.swing.JButton jb_entrada;
    private javax.swing.JButton jb_saida;
    private javax.swing.JButton jb_saidaArmazem;
    private javax.swing.JButton jb_usuario;
    private javax.swing.JLabel jl_minimo;
    private javax.swing.JLabel jl_quantidade;
    private javax.swing.JLabel jlabel_data;
    private javax.swing.JLabel jlabel_hora;
    private javax.swing.JLabel jlabel_usuario;
    private javax.swing.JMenuItem jmi_ajuste;
    private javax.swing.JMenuItem jmi_backup;
    private javax.swing.JMenuItem jmi_destino;
    private javax.swing.JMenuItem jmi_entrada;
    private javax.swing.JMenuItem jmi_fornecedor;
    private javax.swing.JMenuItem jmi_grupo;
    private javax.swing.JMenuItem jmi_produto;
    private javax.swing.JMenuItem jmi_recover;
    private javax.swing.JMenuItem jmi_saida;
    private javax.swing.JMenuItem jmi_unidade;
    private javax.swing.JMenuItem jmi_usuarios;
    private javax.swing.JTable jt_ideal;
    private javax.swing.JTable jt_minimo;
    private javax.swing.JLabel label_data;
    private javax.swing.JMenu menu_cadastros;
    private javax.swing.JMenu menu_movimentos;
    private javax.swing.JMenu menu_relatórios;
    private javax.swing.JMenu menu_relatórios1;
    private javax.swing.JMenu menu_relatórios2;
    private javax.swing.JMenuItem menuitem_sair;
    private javax.swing.JMenuItem menuitem_vencidos;
    private org.netbeans.examples.lib.timerbean.Timer timer1;
    // End of variables declaration//GEN-END:variables

    public void setDesabilitaTela() {
        this.setVisible(false);
        this.setEnabled(false);
    }

    public void setHabilitaTela(boolean status) {
    }

    public void setStatusTela(boolean status) {
        if (status) {
            this.setVisible(status);
        }
        this.setEnabled(status);
    }

    public void carregaUsuario(UsuarioModel usuario) {
        this.usuario = usuario;
        jlabel_usuario.setText("Usuário: " + usuario.getNome_usuario());
    }
    List<ProdutoModel> produtos;

    public void vencidos() {
        ProdutoDAO controlProduto = new ProdutoDAO();
        produtos = controlProduto.listarProdutoVencidos();
        mostrarProdutosVencidos(produtos);
    }

    public void mostrarProdutosVencidos(List<ProdutoModel> produtos) {
        DefaultTableModel tableModel = (DefaultTableModel) jt_ideal.getModel();
        tableModel.setNumRows(0);
        
        for (int i = 0; i < produtos.size(); i++) {
            try {
                SimpleDateFormat in = new SimpleDateFormat("yyyy-MM-dd");
                SimpleDateFormat out = new SimpleDateFormat("dd/MM/yyyy");


                String vencimento = out.format(in.parse(produtos.get(i).getData().toString()));


                ProdutoModel produto = new ProdutoModel();
                produto.setCod_produto(produtos.get(i).getCod_produto());
                produto.setNome_produto(produtos.get(i).getNome_produto());
                produto.setConcentraçao(produtos.get(i).getConcentraçao());
                produto.setEstoque(produtos.get(i).getEstoque());
                produto.setData(produtos.get(i).getData());
                DefaultTableModel row = (DefaultTableModel) jt_ideal.getModel();
                ItemDbGrid hashDbGrid = new ItemDbGrid(produto, produto.getNome_produto());
                row.addRow(new Object[]{hashDbGrid, produto.getConcentraçao(), vencimento, produto.getEstoque()});
                //Integer total = String.valueOf(i)+1;
                jl_quantidade.setText("Total: " + (i + 1));
            } catch (ParseException ex) {
                Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    public void estoqueMinimo() {
        ProdutoDAO controlProduto = new ProdutoDAO();
        produtos = controlProduto.listarMinimo();
        mostrarProdutosMinimo(produtos);
    }

    public void mostrarProdutosMinimo(List<ProdutoModel> produtos) {
        DefaultTableModel tableModel = (DefaultTableModel) jt_minimo.getModel();
        tableModel.setNumRows(0);

//        ((DefaultTableModel) jt_minimo.getModel()).setRowCount(0);
//        jt_minimo.updateUI();

        for (int i = 0; i < produtos.size(); i++) {

//            SimpleDateFormat in = new SimpleDateFormat("yyyy-MM-dd");
//            SimpleDateFormat out = new SimpleDateFormat("dd/MM/yyyy");


            //String vencimento = out.format(in.parse(produtos.get(i).getData().toString()));
            ProdutoModel produto = new ProdutoModel();
            produto.setCod_produto(produtos.get(i).getCod_produto());
            produto.setNome_produto(produtos.get(i).getNome_produto());
            produto.setConcentraçao(produtos.get(i).getConcentraçao());
            produto.setEstoque_minimo(produtos.get(i).getEstoque_minimo());
            produto.setEstoque(produtos.get(i).getEstoque());

            DefaultTableModel row = (DefaultTableModel) jt_minimo.getModel();
            ItemDbGrid hashDbGrid = new ItemDbGrid(produto, produto.getNome_produto());

            row.addRow(new Object[]{hashDbGrid, produto.getConcentraçao(), produto.getEstoque_minimo(), produto.getEstoque()});
            jl_minimo.setText("Total: " + (i + 1));
        }
    }

    public void permissao() {

        jmi_usuarios.setEnabled(false);
        jb_usuario.setEnabled(false);
        jb_ajuste.setEnabled(false);
        jb_entrada.setEnabled(false);
        jb_saida.setEnabled(false);
        jb_usuario.setEnabled(false);
        jButton10.setEnabled(false);
        jButton12.setEnabled(false);
        jButton14.setEnabled(false);
        jmi_backup.setEnabled(false);
        jmi_recover.setEnabled(false);
        jmi_entrada.setEnabled(false);
        jmi_saida.setEnabled(false);
        jmi_ajuste.setEnabled(false);
        jmi_destino.setEnabled(false);
        jmi_fornecedor.setEnabled(false);
        jmi_grupo.setEnabled(false);
        jmi_unidade.setEnabled(false);
    }
    
    public void setIconFrame(){
        //setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../image/registry.png")));
    }
}
