/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UsuariosAlterarGUI.java
 *
 * Created on 26/05/2011, 16:10:08
 */
package br.com.sig.view;

import br.com.sig.dao.UsuarioDAO;
import br.com.medicalpharm.model.UsuarioModel;
import br.com.sig.util.LimitadorTexto;
import br.com.sig.util.UnaccentedDocument;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.InputVerifier;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author ALENCAR
 */
public class UsuariosAlterarGUI extends javax.swing.JFrame {

    public UsuárioGUI janelapai;
    private UsuarioModel objusuario;
    List<UsuarioModel> usuarios;

    /** Creates new form UsuariosAlterarGUI */
    public UsuariosAlterarGUI() {
        initComponents();
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            // UIManager.setLookAndFeel("com.sun.java.swing.plaf.smoothmetal.SmoothmetalLookAndAndFeel");
            //UIManager.setLookAndFeel("com.birosoft.liquid.LiquidLookAndFeel");
            //UIManager.setLookAndFeel(seta_look);
            SwingUtilities.updateComponentTreeUI(this);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro);
        }
    }

    public UsuariosAlterarGUI(UsuarioModel usu) {
        this.objusuario = usu;
        initComponents();

        tf_codigo.setText(String.valueOf(usu.getCod_usuario()));
        tf_nome.setText(usu.getNome_usuario());
        tf_login.setText(usu.getLogin());
        jpf_senha.setText(usu.getSenha());
        if (usu.getPermissao().equals("administrador")) {
            jrm_adm.setSelected(true);
        } else {
            jrm_usuario.setSelected(true);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jb_cancelar = new javax.swing.JButton();
        jb_salvar = new javax.swing.JButton();
        jpf_senha = new javax.swing.JPasswordField(new LimitadorTexto(45), "",10);
        jrm_adm = new javax.swing.JRadioButton();
        tf_nome = new javax.swing.JTextField(new LimitadorTexto(45), "",10);
        jrm_usuario = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_codigo = new java.awt.TextField();
        tf_login = new javax.swing.JTextField(new LimitadorTexto(45), "",10);
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Alterando Usuário");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/medicalpharm/image/exit.png"))); // NOI18N
        jb_cancelar.setText("Cancelar");
        jb_cancelar.setName("jb_cancelar"); // NOI18N
        jb_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jb_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, 33));

        jb_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/medicalpharm/image/gravar_registro.gif"))); // NOI18N
        jb_salvar.setText("Salvar");
        jb_salvar.setName("jb_salvar"); // NOI18N
        jb_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_salvarActionPerformed(evt);
            }
        });
        getContentPane().add(jb_salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        jpf_senha.setName("jpf_senha"); // NOI18N
        jpf_senha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jpf_senhaFocusGained(evt);
            }
        });
        jpf_senha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jpf_senhaKeyPressed(evt);
            }
        });
        getContentPane().add(jpf_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 120, -1));

        buttonGroup1.add(jrm_adm);
        jrm_adm.setSelected(true);
        jrm_adm.setText("Administrador");
        jrm_adm.setName("jrm_adm"); // NOI18N
        getContentPane().add(jrm_adm, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, -1));

        tf_nome.setDocument(new UnaccentedDocument());
        tf_nome.setName("tf_nome"); // NOI18N
        tf_nome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_nomeFocusGained(evt);
            }
        });
        tf_nome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_nomeKeyPressed(evt);
            }
        });
        getContentPane().add(tf_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 280, -1));

        buttonGroup1.add(jrm_usuario);
        jrm_usuario.setText("Usuário");
        jrm_usuario.setName("jrm_usuario"); // NOI18N
        getContentPane().add(jrm_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel5.setText("Código");
        jLabel5.setName("jLabel5"); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel4.setText("Senha");
        jLabel4.setName("jLabel4"); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel3.setText("Login");
        jLabel3.setName("jLabel3"); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        tf_codigo.setEditable(false);
        tf_codigo.setName("tf_codigo"); // NOI18N
        tf_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_codigoActionPerformed(evt);
            }
        });
        getContentPane().add(tf_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 98, -1));

        tf_login.setDocument(new UnaccentedDocument());
        tf_login.setName("tf_login"); // NOI18N
        tf_login.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_loginFocusGained(evt);
            }
        });
        tf_login.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_loginKeyPressed(evt);
            }
        });
        getContentPane().add(tf_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 150, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setText("Nome");
        jLabel1.setName("jLabel1"); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        setSize(new java.awt.Dimension(345, 241));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jb_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cancelarActionPerformed
        janelapai.setEnabled(true);
        janelapai.setVisible(true);
        janelapai.request();
        setVisible(false);
        // TODO add your handling code here:
}//GEN-LAST:event_jb_cancelarActionPerformed

    private void jb_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_salvarActionPerformed
        if (verificarCampos()) {
            verificaCadastro();
        }
        janelapai.listarUsuário();
        //janelapai.list();
        // TODO add your handling code here:
}//GEN-LAST:event_jb_salvarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        janelapai.setEnabled(true);
        janelapai.setVisible(true);
        janelapai.request();        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void tf_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_codigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_codigoActionPerformed

    private void jpf_senhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpf_senhaKeyPressed
        jpf_senha.addKeyListener(new KeyAdapter() {  
      public void keyReleased(KeyEvent evt) {  
        if (evt.getKeyCode() != KeyEvent.VK_HOME) {  
          String s = jpf_senha.getText();  
          jpf_senha.setText(s.toUpperCase());  
        }  
      }  
    }); 
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            alteraUsuario();
            janelapai.listarUsuário();
        }

    }//GEN-LAST:event_jpf_senhaKeyPressed

    private void tf_nomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_nomeFocusGained
        tf_nome.setInputVerifier(new InputVerifier() {

            public boolean verify(JComponent input) {
                if (tf_nome.getText().length() == 0) {
                    JOptionPane.showMessageDialog(null, "Informe o nome do usuário");
                    tf_nome.requestFocus();
                    return false;
                } else {
                    return true;
                }
            }
        });

        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nomeFocusGained

    private void tf_loginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_loginFocusGained
        tf_login.setInputVerifier(new InputVerifier() {

            public boolean verify(JComponent input) {
                if (tf_login.getText().length() == 0) {
                    JOptionPane.showMessageDialog(null, "Informe o login do usuário");
                    tf_login.requestFocus();
                    return false;
                } else {
                    return true;
                }
            }
        });
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_loginFocusGained

    private void jpf_senhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jpf_senhaFocusGained
        jpf_senha.setInputVerifier(new InputVerifier() {

            public boolean verify(JComponent input) {
                if (jpf_senha.getText().length() == 0) {
                    JOptionPane.showMessageDialog(null, "Informe a senha do usuário");
                    jpf_senha.requestFocus();
                    return false;
                } else {
                    return true;
                }
            }
        });
        // TODO add your handling code here:
    }//GEN-LAST:event_jpf_senhaFocusGained

private void tf_nomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_nomeKeyPressed
    tf_nome.addKeyListener(new KeyAdapter() {  
      public void keyReleased(KeyEvent evt) {  
        if (evt.getKeyCode() != KeyEvent.VK_HOME) {  
          String s = tf_nome.getText();  
          tf_nome.setText(s.toUpperCase());  
        }  
      }  
    }); 
    // TODO add your handling code here:
}//GEN-LAST:event_tf_nomeKeyPressed

private void tf_loginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_loginKeyPressed
    tf_login.addKeyListener(new KeyAdapter() {  
      public void keyReleased(KeyEvent evt) {  
        if (evt.getKeyCode() != KeyEvent.VK_HOME) {  
          String s = tf_login.getText();  
          tf_login.setText(s.toUpperCase());  
        }  
      }  
    }); 
    // TODO add your handling code here:
}//GEN-LAST:event_tf_loginKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new UsuariosAlterarGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jb_cancelar;
    private javax.swing.JButton jb_salvar;
    private javax.swing.JPasswordField jpf_senha;
    private javax.swing.JRadioButton jrm_adm;
    private javax.swing.JRadioButton jrm_usuario;
    private java.awt.TextField tf_codigo;
    private javax.swing.JTextField tf_login;
    private javax.swing.JTextField tf_nome;
    // End of variables declaration//GEN-END:variables
    UsuarioModel usuario = new UsuarioModel();

    public void alteraUsuario() {
        if (verificarCampos()) {
            UsuarioDAO usuarioControl = new UsuarioDAO();
            usuario.setCod_usuario(Integer.parseInt(tf_codigo.getText().trim()));
            usuario.setNome_usuário(tf_nome.getText().trim());
            usuario.setLogin(tf_login.getText().trim());
            usuario.setSenha(jpf_senha.getText().trim());
            if (jrm_adm.isSelected()) {
                usuario.setPermissao("administrador");
            } else {
                usuario.setPermissao("usuario");
            }
            usuarioControl.alteraUsuario(usuario);
            JOptionPane.showMessageDialog(null, "Cadastro alterado com sucesso");
            retornaJanelaPai();
        }
    }

    public void verificaCadastro() {
        UsuarioDAO usu = new UsuarioDAO();
        usuarios = usu.listarUsuarioDescrição1(tf_nome.getText().trim(), tf_login.getText().trim());
        validaCadastro(usuarios);
    }

    public void validaCadastro(List<UsuarioModel> usuario) {//verifica cadastro existente que retornou de uma lista

        if (usuario.size() == 1) {
            alteraUsuario();
        } else {
            JOptionPane.showMessageDialog(null, "Usuário ou login existente");
            tf_nome.requestFocus();
        }
    }

    public boolean verificarCampos() {
        String msgERRO = "Preencha os campos obrigatórios:\n";

        if (tf_nome.getText().trim().equals("")) {
            msgERRO = msgERRO + " *Nome\n";
        }
        if (tf_login.getText().trim().equals("")) {
            msgERRO = msgERRO + " *Login\n";
        }
        if (jpf_senha.getText().trim().equals("")) {
            msgERRO = msgERRO + " *Senha\n";
        }


        if (!msgERRO.equals("Preencha os campos obrigatórios:\n")) {
            JOptionPane.showMessageDialog(this, msgERRO);
            return false;
        } else {
            return true;
        }

    }


    public void retornaJanelaPai() {
        janelapai.setEnabled(true);
        janelapai.setVisible(true);
        janelapai.request();
        setVisible(false);

    }

}
